name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      # Run Linting using Pre-commit Hooks
      - name: Run Linting (Pre-commit)
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files

      - name: Run Lint (Black and Flake8 Manually)
        run: |
          black --check .
          flake8 .

      - name: Run Tests
        run: |
          pytest --maxfail=5 --disable-warnings
